version: '3.7'

services:
  api:
    image: arnebogaerts/api-basisproject:latest
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://ArneCD:CDstoreArne@db/cdstoredb
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: some-root-password
      MYSQL_DATABASE: cdstoredb
      MYSQL_USER: ArneCD
      MYSQL_PASSWORD: CDstoreArne
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
